# Generated by Django 5.2.5 on 2025-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0002_remove_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assigned_puzzles',
            field=models.JSONField(default=dict),
        ),
    ]
