# Generated by Django 5.2.5 on 2025-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0003_player_assigned_puzzles'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='victory_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
