# Generated by Django 5.2.5 on 2025-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0004_player_victory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
